### ISSUE TITLE
something wrong when i compile R0 aimstar

### ISSUE THREAD

**Issue by xin6x6** [CowNowB/Aimstar#9]
![image](https://github.com/user-attachments/assets/da9c1296-24a9-472a-a7f8-9731524e33af)
it said no "ntifs.h" this file. it doesn't exist. qwq
![image](https://github.com/user-attachments/assets/06e3948e-77f3-402c-ace1-c66882e123aa)

**Comment by xin6x6** [comment]
![image](https://github.com/user-attachments/assets/fac7a44f-6b82-4458-ae67-c0e77e85cd59)
also when i check imports.h it said ntifs.h,ntddk.h,ntstrsafe.h couldn't find

**Comment by MehPropy** [comment]
First of all, the reason you cant see those files is not because you dont have them, its because they are dependencies and can not be seen in the project folder.

Secondly, most of nt*.h dependencies are usually connected to building a kernel driver, now this issue of you not being able to include them may happen if visual studio dosent realize that Driver is a kernel driver project. You can fix this by downloading the WDK (windows driver kit) so that visual studio can detect a kernel driver project.

Windows Driver Kit [here](https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk) (Official Microsoft download)

After that just "Rebuild solution" from visual studio and you should be good to go. Write here if you still cant fix the issue.
Cheers.
